// React/src/App.tsx
import {
  useEffect, useState, useCallback, useRef,
} from 'react';
import './App.css';
import 'devextreme/dist/css/dx.material.blue.light.compact.css';
import LoadPanel, { Position } from 'devextreme-react/load-panel';
import Pagination from 'devextreme-react/pagination';
import { fetchColorData, getRandomPastelColor } from './colorService';

const total = 100;

interface Color {
  image: string;
  name: string;
}

function App(): JSX.Element {
  const [loadPanelVisible, setLoadPanelVisible] = useState<boolean>(false);
  const [pageSize, setPageSize] = useState<number>(5);
  const [pageIndex, setPageIndex] = useState<number>(3);
  const [visibleCards, setVisibleCards] = useState<Color[]>([]);

  const hexCodes = useRef<string[]>([]);
  const colorsCache = useRef<Map<string, Color>>(new Map());

  useEffect(() => {
    for (let i = 0; i < total; i++) {
      hexCodes.current.push(getRandomPastelColor());
    }
  }, []);

  const fetchColorsForPage = useCallback(async (): Promise<void> => {
    setLoadPanelVisible(true);
    const startIndex = (pageIndex - 1) * pageSize;
    const endIndex = startIndex + pageSize;
    const hexSubset = hexCodes.current.slice(startIndex, endIndex);

    const promises = hexSubset.map((hex) => {
      if (colorsCache.current.has(hex)) {
        return Promise.resolve(colorsCache.current.get(hex));
      }
      return fetchColorData(hex).then((color) => {
        if (color) {
          colorsCache.current.set(hex, color);
        }
        return color;
      });
    });

    try {
      const results = await Promise.all(promises);
      const filteredColors = results.filter((color): color is Color => color !== null);
      setVisibleCards(filteredColors);
    } catch (error) {
      // eslint-disable-next-line no-console
      console.error('Error fetching colors:', error);
    } finally {
      setLoadPanelVisible(false);
    }
  }, [pageIndex, pageSize]);

  const onPageIndexChange = useCallback((value: number) => {
    setPageIndex(value);
  }, []);

  const onPageSizeChange = useCallback((value: number) => {
    setPageSize(value);
  }, []);

  useEffect(() => {
    fetchColorsForPage().catch((error) => {
      // eslint-disable-next-line no-console
      console.error('Error updating visible cards:', error);
    });
  }, [fetchColorsForPage]);

  return (
    <div className="main">
      <LoadPanel
        visible={loadPanelVisible}
        showIndicator={true}
        showPane={true}
        hideOnOutsideClick={false}
      >
        <Position my="top" at="top" of="#cards" />
      </LoadPanel>
      <Pagination
        showInfo={true}
        showNavigationButtons={true}
        pageIndex={pageIndex}
        pageSize={pageSize}
        itemCount={total}
        onPageIndexChange={onPageIndexChange}
        onPageSizeChange={onPageSizeChange}
      />
      <div id="cards">
        {visibleCards.map((color, index) => (
          <div key={index}>
            <img src={color.image} alt={color.name} />
          </div>
        ))}
      </div>
    </div>
  );
}

export default App;

// Angular/src/app/app.component.ts
/* eslint-disable @typescript-eslint/no-non-null-assertion, no-else-return, no-console, no-void */
import { Component } from '@angular/core';
import { DxLoadPanelModule } from 'devextreme-angular/ui/load-panel';
import { DxPaginationModule } from 'devextreme-angular/ui/pagination';
import { firstValueFrom } from 'rxjs';
import { ColorService, Color } from './app.service';

@Component({
  selector: 'app-root',
  imports: [DxLoadPanelModule, DxPaginationModule],
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss'],
  providers: [ColorService],
})
export class AppComponent {
  loadPanelVisible = false;

  total = 100;

  colors: Map<string, Color> = new Map();

  hexCodes: string[] = [];

  visibleCards: Color[] = [];

  pageIndex = 3;

  pageSize = 5;

  constructor(private readonly colorService: ColorService) {}

  ngOnInit(): void {
    this.generateHexCodes();
    void this.fetchColorsForPage();
  }

  generateHexCodes(): void {
    for (let i = 0; i < this.total; i++) {
      this.hexCodes.push(this.colorService.getRandomPastelColor());
    }
  }

  async fetchColorsForPage(): Promise<void> {
    const startIndex = (this.pageIndex - 1) * this.pageSize;
    const endIndex = this.pageIndex * this.pageSize;
    const hexSubset = this.hexCodes.slice(startIndex, endIndex);

    const promises: Promise<Color>[] = hexSubset.map((hex) => {
      if (this.colors.has(hex)) {
        return Promise.resolve(this.colors.get(hex)!);
      } else {
        return firstValueFrom(this.colorService.fetchColorData(hex)).then((data) => {
          const colorData: Color = data;
          this.colors.set(hex, colorData);
          return colorData;
        });
      }
    });

    this.loadPanelVisible = true;
    try {
      const fetchedColors = await Promise.all(promises);
      this.visibleCards = fetchedColors;
    } catch (error) {
      console.error('Error fetching colors:', error);
    } finally {
      this.loadPanelVisible = false;
    }
  }

  onPageIndexChange(val: number): void {
    this.pageIndex = val;
    void this.fetchColorsForPage();
  }

  onPageSizeChange(val: number): void {
    this.pageSize = val;
    void this.fetchColorsForPage();
  }
}

<div class="container">
  <dx-load-panel
    [(visible)]="loadPanelVisible"
    [showIndicator]="true"
    [showPane]="true"
    [hideOnOutsideClick]="false"
    ><dxo-position my="top" at="top" of="#cards"> </dxo-position>
  </dx-load-panel>
  <dx-pagination
    [showInfo]="true"
    [showNavigationButtons]="true"
    [itemCount]="total"
    [pageIndex]="pageIndex"
    [pageSize]="pageSize"
    (pageIndexChange)="onPageIndexChange($event)"
    (pageSizeChange)="onPageSizeChange($event)"
  >
  </dx-pagination>
  <div id="cards">
    <ng-container *ngFor="let color of visibleCards">
      <img [src]="color.image.bare" [alt]="color.name.value" />
    </ng-container>
  </div>
</div>
